dependencies:
  - base == 4.*
  - mtl
  - list-zipper
  - lens

executables:
  haskell-hello:
    main: Main.hs

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Werror
tests:
  spec:
    main: Driver.hs
    source-dirs: spec
    dependencies:
      - hspec
      - hspec-discover
      - drumming-rendering-again
