dependencies:
  - base == 4.*
  - mtl

executables:
  haskell-hello:
    main: Main.hs

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Werror

tests:
  spec:
    main: Spec.hs
    source-dirs: spec
    dependencies:
      - tasty
      - tasty-hunit
      - HUnit
      - drumming-rendering-again
