dependencies:
  - base == 4.*
  - mtl
  - lens
  - heterocephalus
  - blaze-markup
  - repline
  - process
  - rio
  - rio-orphans
  - haskell-gi-base
  - gi-gtk
  - gi-gdk

executables:
  score:
    dependencies:
      - drumming-rendering-again
    main: Main.hs

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Werror
tests:
  spec:
    main: Driver.hs
    source-dirs: spec
    dependencies:
      - hedgehog
      - tasty
      - tasty-discover
      - tasty-golden
      - tasty-hedgehog
      - drumming-rendering-again
